### ISSUE TITLE
Easter Egg Music Doesn't Play

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#111]
[ERROR] addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/easter_eggs/cl_ee.lua:30: attempt to perform arithmetic on local 'streamstart' (a nil value)
1. onsuccess - addons/nzombies-master-changes/gamemodes/nzombies3/gamemode/easter_eggs/cl_ee.lua:30
   1. unknown - lua/includes/modules/http.lua:34

**Comment by Zet0rz** [comment]
There is no problem with it. Did you type in an invalid URL? It happens if the URL in the http.Fetch isn't valid. I got it when I replaced all // comments with --, which also replaced the URL "://". Make sure the URL is as it says it needs to be here on Github, and then make sure you use a valid URL that can be streamed (people can turn this off if they want).

**Comment by Zet0rz** [comment]
Commit f96329219cddac8b3c152c83e43e1e18b124318b makes it print "This Soundcloud song does not allow streaming." when this happens rather than throw an error. Make sure your URL is valid.

**Comment by minin43** [comment]
It should be valid, I'll have to double check. There's a chances I mighta not copied the first w, or something.
