### ISSUE TITLE
Round Six and weapon cycle

### ISSUE THREAD

**Issue by RukoSanada** [Zet0rz/nzombies#112]
Upon reaching round six nothing really happens. I also tried disabling the special rounds just to avoid it doesn't seem to care as it happens anyway. I spawned the burning zombies with the spawn tester to see what their deal was. They seemed to enjoy the life of doing nothing.  

Sometimes buying a weapon or grabbing a weapon from the box just kind of force swaps you to your grenades and you have to melee to get back to your weapons, but you never get the weapon you bought/purchased. [This usually only happens once you've reached your max weapon limit]

**Comment by Zet0rz** [comment]
> Upon reaching round six nothing really happens.

I'll go investigate this. Something may have broken along the way, at the moment I'm testing with nz_test_hellhounds on which replaces special rounds with hellhounds.

> Sometimes buying a weapon or grabbing a weapon from the box just kind of force swaps you to your grenades

I've never seen this before ever except with a specific weapon pack (Black Ops Cold War pack I think), which I did fix on my end, but the guy who reported it said it was still going on. Does this happen with a specific weapon pack, and if so, which one?

**Comment by Zet0rz** [comment]
Commit 389c7d2a2f4d69a44395901e2fe280b0c0ad9874 fixes the fire zombies doing nothing. Also fixed the config having a hard-coded special round from back before the automatic special rounds system was added. Can't look into the grenade bug until I know which weapon pack it happens with, as I need to be able to test it.

**Comment by RukoSanada** [comment]
Looks like it's happening with (GDCW) Nikolai's WWII Swep Pack. [Also it seems like the changes to fix the burning zombie made the random box lose it's properties ''No weapon is available'' Upon checking the tool itself seems like you can longer make edits as to what weapons spawn or doesn't spawn.]

**Comment by Zet0rz** [comment]
> made the random box lose it's properties

I don't think the random box tool ever had those settings? The list of weapons that the random box can use is set in the Map Settings tool when Advanced Mode is on.

I'm gonna take a few tests with this weapon pack and see what I can come up with.

**Comment by minin43** [comment]
Make sure you have @Zet0rz version and not Alig's, I made this mistake.

**Comment by RukoSanada** [comment]
I have the right version, I'm quite sorry I just had a minor brain explosion. Yeah I completely forgot that it was within the Map settings. Lack of sleep does that. I'll continue to keep an eye out for any other bugs I come across, as well as any other weapons that may also have this issue.

**Comment by RukoSanada** [comment]
It seems like this issue is bigger than I thought this effects a massive amount of sweps from what I've been experiencing. The follow sweps that I have tested that have been affected by this bugs are [ Modern Warfare 2 Weapons Pack, Star Wars Weapons [SW weps seem to work with themselves but not with other packs weps.], CSO Weapon Pack, CSO/CF Weapons Pack, Halo SWEPs- UNSC, And every M9K wep pack suffers from this.

These are the packs that I've seen affected by this. What's even more odd is that the Doom 3 weps can be purchased no matter what with any one of these weapons and the issue is disregarded with them and vice versa. Other than that all the mentioned weps suffers from this bug.
[Makes it kind of difficult to gather a healthy list of sweps] Hope this report helps with finding the core problem.

**Comment by Zet0rz** [comment]
I have just tested a whole bunch with all sorts of weapons from M9K and I just can't get this to happen at all. But I was just playing on another server playing this gamemode, and it did happen there every time, even for me. I think it might be a name conflict where the two mods use same named variables.

Either way, in commit b569a64cd02a8a9d83ded361f78d9aaae719cb7b I have changed how the special weapon system handles weapon switching, which I don't think directly fixes your grenade problem (as I can't reproduce), but we may be lucky that we got around it. It should have some failsafes in it. Can you confirm whether this still happens in this version?

**Comment by RukoSanada** [comment]
I'll get right on it right now, I'll edit this post with results. 

[Seems like these changes broke the Melee function it just doesn't work anymore and the following problems are still there.]
[Update Nevermind the Melee function. I retried it again under a fresh install just to be safe. Melee seems fine again? Could've just been a rare thing. However the exact same problem with the weapons exist.]

**Comment by Zet0rz** [comment]
Right. I have absolutely not been able to reproduce the issue on my client, however it happened all the timer in another server I was betatesting in. That included the inability to melee. I think that might happen just before the grenade swap, because it happened when I got my second weapon from the box. But in general, I really have no clue why gmod would switch to the nades when the PlayerSwitchWeapon hook blocks it unless the key is pressed.

**Comment by RukoSanada** [comment]
Could by some odd chance another mod possibly interfere with this gamemode causing these things to happen? It just seems odd based on what you're saying that this is happening only in selective areas I.E for me and that server you speak of. Unless it's just something else we really can't figure out.

**Comment by Zet0rz** [comment]
I was very certain it was because of the variable player.UsingSpecialWep might be used by those other mods, but I changed that to a NetworkVar the other day and you said that didn't change anything. I doubt it would be the classname itself on the grenades as I don't know of any code using nz_ prefix other than this.

However when I did encounter this (which I then fixed) on my laptop, I put debug messages in the PlayerSwitchWeapon hook which then seemed to imply that it switches from _no weapon_ to the grenade, which means it's likely because the old weapon was removed as it got swapped for a new one, but on the moment it was gone, gmod would auto-pick the grenade (because gmod just picks another weapon when one is removed). But I fixed that by setting its weight low so it wouldn't get prioritized. Still seems to happen for some :/

**Comment by Zet0rz** [comment]
Found the bug in the Black Ops Teaser weapon pack. It appears to be that weapon pack modifying (or maybe hooking) into the weapon switching mechanics, as it doesn't even call our hook at all. I will investigate further and hopefully get a fix soon, otherwise it's that weapon pack that needs updating.

Funny enough, using console command `use` makes you able to switch weapon. But lua_run'ing `player:SelectWeapon` does not.

**Comment by Zet0rz** [comment]
Found the bug. It appears to be _(really)_ bad coding on the weapon pack. Take a look at this:
`hook.Add("CreateMove", "NeuroMicroFixUpsideDownView", function( usercmd ) 
    local ply = LocalPlayer()
    return usercmd
end )`
This code takes your local player, then does nothing. And then it returns, meaning all other hooks under CreateMove will not run (including our weapon switch one). This gun mod is incompatible with anything that modifies controls pretty much xD
