### ISSUE TITLE
Being downed in creative mode

### ISSUE THREAD

**Issue by Alig96** [Zet0rz/nzombies#116]
You can be downed in creative mode. I was nocliped and hit the ground too hard and got downed. When you die you go back to normal, but its an issue worth mentioning.

**Comment by Zet0rz** [comment]
Use /revive chatcommand

**Comment by Alig96** [comment]
I don't understand, is this intended behavior? Since someone made a pull for it to be added to the read me??

**Comment by Zet0rz** [comment]
I'm not gonna prevent downing in creative mode, it'd be better to use the same mechanics globally in the entire gamemode, also so that players can test/experience the mechanics in creative mode (just like they can buy things if they get points). /revive was just added so that you don't have to lua_run it every time to get back up. It is also in the cheats menu.
