### ISSUE TITLE
Maximum Player Notice

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#137]
Can you include a "maximum player amount" in the config loader?

**Comment by Alig96** [comment]
Just limit the server player slots of the server?

**Comment by Zet0rz** [comment]
> Just limit the server player slots of the server?

I think he means so servers can dynamically change or so that the loader will display how many players a map was made for (for smaller maps).

There's some limitations with the config loader, and that is that it can only load the file name. It gets every bit of information from the file name and location. Local if the file is in /data/nz/, Workshop if in /lua/nz/ and official if in /gamemodes/nzombies3/officialconfigs/. The name is what's behind the semi-colon, and the map is what's in front. This means I cannot load any more information into it than I can put in the name. Stuff like difficulty, creator, description, and more can't be put in without having to load the actual file. And that can potentially cause a good deal of lag and network usage to send across every time.

**Comment by Alig96** [comment]
> This means I cannot load any more information into it

Are you sure? Just add more semi-colons and string explode??

**Comment by Alig96** [comment]
Oh I understand, you want to add meta-information. This is where a wrapper would come in handy.

**Comment by minin43** [comment]
Can't you just get a variable that adds up all of the placed player spawns and when loading, under each config file has a line that says "Maximum players: #" so people know what each config is set up for?

**Comment by Alig96** [comment]
With the current loading system it wouldn't be able to read the variable until after it has already been loaded, which means it can't be displayed in the menu before loading, you would only know the number after they press load.

**Comment by minin43** [comment]
Surely there's some way it could be made so that the gamemode always "loads" a tiny portion of the config file (or a second one entirely) that provides the server with this information? Or am I fantasizing?

**Comment by Zet0rz** [comment]
> Oh I understand, you want to add meta-information. This is where a wrapper would come in handy.

I don't really _want_ to add it, I think it's good as it is. Using a wrapper though would be the same as loading the actual config (without generating it).

> Are you sure? Just add more semi-colons and string explode??

I can do that, but I can't fit everything in there. You can imagine how silly it'd look like `nz_ttt_kosovos;Breakout;Zet0r;2-6;Hard.lua`. I won't be putting a lot in the file name, have to keep them simple.

> Surely there's some way it could be made so that the gamemode always "loads" a tiny portion of the config file (or a second one entirely)

You can't load part of a file, however we can load the entire file and just not generate it, then look at some metadata. But while this is possibly, it means it'll need to load _all_ configs _every_ time someone opens the load menu. I'm not sure how efficient this is, and it's gonna require a lot of network usage.

**Comment by minin43** [comment]
Call me inexperienced at coding Lua (or in general), because I am, but is there not a way to search files for specific lines of text? I know you can do it in Java, but Java is different from Lua.

**Comment by Zet0rz** [comment]
You can, but that _is_ reading the file. It is definitely possible, just not sure how efficient it really is, or how to even network it. And on top of that, there isn't really much more space in the loader :/

**Comment by lolleko** [comment]
Maybe create a file in addition to a map config that holds all that information and info.txt. Change the map cfg system to use folders that contain multiple txts rather than just one txt for everything. So there would be a  folder called `mymapconfigstuff/` and that contains inside `info.txt` `config.txt`. This would also remove the need for those odd semicolons in filenames. But thats a lot of work so i am not sure.

**Comment by minin43** [comment]
The more user-friendly the better. A lot of 12 year olds will be playing this gamemode. I would heavily recommend creating something for this, but I will relent if it honestly is too much work.

**Comment by Zet0rz** [comment]
I don't think extra work on our side is bad if it means more user-friendliness to players. But in this case, it isn't really needed in my opinion. So it's not that I don't want to do it, it's that it's such a small deal that it just isn't worth it, even less so when you think of what the server has to network and how cramped the load screen would become.

I don't think this will become a thing.

**Comment by minin43** [comment]
@Zet0rz For my workshop releases, I can include a maximum player counts in the addon descriptions.

**Comment by Zet0rz** [comment]
If you guys _really_ want metadata (not maximum players, probably just Creator, maybe difficulty or description), then I can look into trying it. But I'm not sure if it's good or bad, of how I can get space in the load interface. And if I do make it, it'll be metadata saved directly into the same config file, which is then read on /load (for all configs). I can probably make it a convar too, so that you can turn it off if it slows down too much

**Comment by Zet0rz** [comment]
> For my workshop releases, I can include a maximum player counts in the addon descriptions.

Yeah in general, most metadata should be on the Workshop page for the file. I could possibly, if I make the few pieces of metadata, include the Creator and make the Workshop text become a link linking to the workshop (you'd then input the Workshop ID in Map Settings after updating it)

**Comment by minin43** [comment]
Don't feel pressured into doing this if it's too much work, or trying to fit it in before the gamemode workshop release. Take your time, I'll take quality of quantity.

**Comment by Alig96** [comment]
Okay I'm going to make 1 last cry for a wrapper system. You can then also combine the map scripts and the config in 1 file instead of having them separated. So you can have meta-data, the config and map script all in 1 file to keep them organised

**Comment by Zet0rz** [comment]
Downloading a seperate zip is not good for user-friendliness. Whichever solution we pick, it has to be generated by the gamemode itself. I imagine I could do some experimenting with file.Read'ing the config files, checking for a Metadata table, then use that and ignore the rest. If you have 20+ configs, that's a lot of files to load though, but Alig pointed out that it might be a good idea to only do this for current map configs.
