### ISSUE TITLE
Hellhounds Root You

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#148]
When Hellhounds attack you, they root you in place, and you're unable to move until you kill them. If you don't have Juggernog, it doesn't take more than 2 seconds for a single hellhound to kill you, usually making round 6 INCREDIBLY difficult to complete.

**Comment by Zet0rz** [comment]
It is because their CollisionBounds are smaller than their physics model. So the bot will pathfind into you until its CollisionBounds hit you, but at that point you're inside its physics model, rendering you stuck. It will likely require a recompile, but that'd make its physics and awkward tiny pillar in its center. Still, that beats being stuck.

**Comment by Zet0rz** [comment]
Nevermind, seems like it can be fixed by setting its solid type to SOLID_BBOX. Commit f0ff9184511a01c1c68de87ec5550b2206193de6 does this.
