### ISSUE TITLE
Can we change some of the PaP names?

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#150]
Some of these are kind of stupid :\

AR-15 to "All-Right15"?
G3A3 to "G3T-B3TT3R"?
MR96 to "Mr. Rekker 96"?
Kimber K(night)W(arrior) to "Kimber Knight Warlord"?
XM1014 to "XTREME1015"?

How about ones like: MR96 to "MR73 Gendarmerie" or the M1911 to "Colt Mk. IV Series 80"? Y'know, the gun's actual variants in real life, not some lame, made-up-on-the-spot ones. At least in CoD the gun's new names were plays on their old ones and were thought out. Like in BO2, the "HAMR" HMG is renamed "The Sickle" as a play on words (Get it? Hammer and Sickle? Soviet Union's flag?).

I tried doing a pull request for it earlier but it was closed? Why?

**Comment by Zet0rz** [comment]
in CoD the names _are_ silly (mostly), and many use leet as well. ".357 Magnum" ---> ".357 Plus 1 K1L-U", "SMR" ---> "SM1L3R". Of course many are also well thought-out, more so than what I've managed to come up with, so feel free to suggest new names to use, but I'm not much for using other gun variants; it has to be funny in some way.

**Comment by minin43** [comment]
Can we avoid doing the cringey "L33T SP3@K," at the very least? I've grown to hate it. Sure it might fit for a gun here and there (CoD RARELY uses it, most guns have actual names such as "The Reaper," which sounds badass and cool), but please let's stay away from it.

**Comment by Zet0rz** [comment]
I can't really go away from a certain aspect because some people hate it personally, even if I did myself I need to stay true to CoD as much as possible. However I agree there's a bit too much leet, I just couldn't really come up with too many good ones, but I can reduce the amount of leet names, I'll need some good suggestions (or just a good amount of time). If you have some suggestions, make sure they are something well thought-out or are funny in a way; acronyms work good as well.

And remember you can always update it locally on your own server :)

**Comment by minin43** [comment]
Default Weapons
Renaming renames
- AK-74 -> "AK-4TW"
- AR-15 -> "XM16E3" or "AR-15 Porter"
- Deagle -> "Deagle Mk. XIX"
- G3A3 -> "G3/SG-1"
- L115 -> "L-ement 115"
- MP5 -> "MP10"
- MR 96 -> "MR73 Gendarmerie"
- UMP .45 -> "Unified Material Penetrator 4D5"

Guns that don't have a name:
- FN Five-Seven -> "FN Ten-Fourteen"
- G36C -> "G36C-MOR"
- M3 Super 90 -> "M3 Super Nova"
- M14 -> "M14 EBR"
- M1911 -> "Colt Mk. IV Series 80"
- MAC-11 -> "Vulcan M-11-9"
- P99 -> "P99 RAD"
- SCAR-H -> "SCAR FNAC"

I just kept the IRL variants if they sounded badass.

**Comment by func-octo** [comment]
If you're familiar with the P90X Workout Programs (probably not since it's from America), you could name the P90 to 'P90X Ripper', or something not that stupid xD

The AK-47 could be renamed to Almighty-Killer 47W

@minin43
I think the L115 could be renamed to L-ement 115 instead of Element 115. :+1:

**Comment by lolleko** [comment]
@ScriptnLua http://callofduty.wikia.com/wiki/Element_115
It wouldn't match the lore if you change that.

**Comment by func-octo** [comment]
@lolleko 
Thanks! But I already know what Element 115 is :)
It is what reanimated the dead, created the Hellhounds, etc.

True, but it's a Pap name joke. Still sounds like it too.

veni vidi vici - Julias Caesar

**Comment by minin43** [comment]
There is no P90 to rename

**Comment by Zet0rz** [comment]
> AK-74 -> "AK-4TW"

AK-47 is AK-4TW. The 74 is AK-74fu2

> L115 -> "L-ement 115"

Renamed to "L-Emnt 115" to make it a bit less obvious, but still the same joke.

> M1911 -> "Colt Mk. IV Series 80"

I feel like I should make Mustang and Sally just because of how iconic those were.

Will look more at them later, on to making the first major easter egg. Also, in your suggestions, please also put the classname so I don't have to go find it in the game, makes it a bit easier for me to do quickly xD

**Comment by minin43** [comment]
The AK-74 was already named the "AK-4TW" in your file, I just put it here for consistency reasons.

> should be named Mustang and Sally

Buuuuuut, the Mustang and Sally was 2 guns, named "Mustang" and "Sally." It shouldn't be named Mustang and Sally if you don't get dual pistols.

**Comment by Zet0rz** [comment]
If I can't make the dual wield, I'll just make Mustang or the C3000-b1at-35 (WaW version).

**Comment by minin43** [comment]
Go with mustang

**Comment by minin43** [comment]
Although now that I think of it, I have an old CW2.0 addon that was dual-pistols. It's old so there are a few errors but other than that it works great

**Comment by Alig96** [comment]
Alright lads, we all know the Ak-47 should be the AG-96 hint hint nudge nudge

**Comment by minin43** [comment]
What?

**Comment by Alig96** [comment]
^Hint

**Comment by minin43** [comment]
Is it supposed to be your name?

**Comment by Worset** [comment]
How about a setting to change the names of any weapon after they are PaP'd? Food for thought. :)

**Comment by Zet0rz** [comment]
> How about a setting to change the names of any weapon after they are PaP'd? Food for thought. :)

As in while the game is running with a console command? It wouldn't be able to save it that way, at least not with how it is now. However there's already a function you can use in any lua script you may choose to put in autorun.
