### ISSUE TITLE
Hammer FGD support.

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#156]
My friend would like to know if he would be able to use hammer to place things like zombie spawns and such instead of gmod. He says he would like to do this is hammer because it is easier for him, and so he could bind the config to his map when he pushes it to the workshop? Is this possible?

**Comment by Alig96** [comment]
Should be possible. Would need an accompanying .fgd file. I think it should be added to the todo list. Here's an example as reference for anyone who wants to make one for nzombies: https://github.com/garrynewman/garrysmod/blob/master/garrysmod/gamemodes/terrortown/ttt.fgd

**Comment by Zet0rz** [comment]
While it is highly possible, I don't think it will be a very good idea as it would prevent any other config from being made on the map because the entities are bound to the map; they would spawn regardless of the config loaded, and on every cleanup. Map creators should really create configs like normal and ship them with the map. A potential idea is to make the .fgd contain a single entity that defines what config it would _autoload_ on map start.

**Comment by func-octo** [comment]
@Zet0rz I agree. But if the map creator only wants his config to be used this would work, right? He knows a million times more about hammer and lua than I do, and he sais he would include a checker to see what gamemode the map was launched in.

**Comment by Zet0rz** [comment]
@ScriptnLua Of course a checker (wouldn't even be needed, the entities would only exist in our gamemode), but the problem lies in other configs in this same gamemode. I wouldn't want to allow people the option of forcing their configs onto other people. And even if so, I'm not sure it'd even work as cleaning up the map excludes these entities, but the cleanup function would then create them again, stacking entities on top of each other. It would generally require a very hacky solution.

**Comment by func-octo** [comment]
🆗 ✔️ 

💻  + 01101110 = Matrix

Sometimes they run into physics props and this happens btw.
**nz_ZombieWalker** 🚽 **Scriptn' Lua**

**Comment by Zet0rz** [comment]
They kill you with props? lol

**Comment by func-octo** [comment]
Like those cones on some tf2 maps. They touch it, the cone spazzes out, and murders me. (Those darn sniping cones!)

**Comment by lolleko** [comment]
Lol as far as I can remember there werent any prop_physics in official tf2 maps (at least not moving ones).

**Comment by func-octo** [comment]
In the Tough Break update, they made it so all cones in all maps now have physics from explosions and what not. They respawn when no one is looking where they once were (stealthy, sniping cones...)

**Comment by Zet0rz** [comment]
Well @ScriptnLua, what is your friend's opinion on not having a .fgd? Or would he like one to determine which to autoload (and potentially have a seperate label like _Map Official _ or something to mark it)?

**Comment by func-octo** [comment]
Yes. He would be doing this to make an official map with only that config on autoload function and then just the map itself separately in one addon. Sorta like DLC, but not DLC...

**Comment by Zet0rz** [comment]
I will look into making a simple .fgd and entity for this, but first there's something. If we create this .fgd, it will allow us to load a config automatically and show up as map official yes, but it will only appear as map official when the map is actually loaded (since the entity with the name only exists when the actual map is loaded). At other times it'd be just a simple Workshop label. If we want it to be map official from wherever, we might want to not make a .fgd and instead make a new way to pack configs together with maps, just like how official configs are in the gamemode itself.

The thing is, packing it inside a different folder in lua would just allow anyone to do that, making all their configs appear as map official on whichever maps they want. So what would you rather; have it only show up on the map itself, or make a new way that can be potentially cheated around? Or do you have an idea how you can pack it in some way that only the map creator can?

**Comment by lolleko** [comment]
If the map gets uploaded to the workshop your friend can jsut add the "official map config" into a lua folder and uplaod it with the map. In my opioniona feature like "map official configs" or "map configs in hammer" would be a lot of work, but not really sued by amny people (if at all).
