### ISSUE TITLE
Wallbuy GUI not Working (Testing for fixes in progress...; Doors, Cheats, GUI Fixed)

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#163]
I played the official ttt_kosovos config, to find that I couldn't open any doors or use any of the cheats. The cheats kept on saying invalid, even though the perk/weapon existed. Any ideas on how to fix this? 
I've installed it correctly, and have reinstalled it twice, but nothing changes. Also wallbuy outlines are now vidible to me, but once I get within 2 feet of one, the hallo/outline effect goes away. I've switched it to nz_outlinedetail 1 so I can see the model, which doesn't disappear.

**Comment by minin43** [comment]
Have you tried reinstalling?

**Comment by Zet0rz** [comment]
`nz_outlinedetail` goes up to 4, setting it to 1 causes it to only create 1 "outline copy" model which will then make outlines only appear in one corner of the weapon's model. But try reinstalling, doors are confirmed working on latest version for me.

Otherwise, try checking your addons. Any addon can interfere with what you can use (press E on), even block it alltogether. Most of them do it fairly (like us, we allow you to use map-based doors), but accidentally cause a conflict.

**Comment by func-octo** [comment]
Lol I should look in the console more often.
'Key e not bound!'

**Comment by func-octo** [comment]
Scratch that last comment! I have disabled two addons, now the gui won't show up and doors as well as perks do not open/get used. I know I have enough points because I have killed 2 waves of zombies by now, and it's starting to get crowded in here!

When I get home, I'll try disabling all of them, but I doubt it'll help.

**Comment by Zet0rz** [comment]
Try putting this into your console: `lua_run PrintTable(hook.GetTable())`
Then look for anything under `FindUseEntity` and `PlayerUse` and tell us which ones are listed there. That would tell us if a hook might be blocking the other hooks.

**Comment by func-octo** [comment]
I can try that later today if I have time.

**Comment by Zet0rz** [comment]
I got another person reporting he couldn't open doors, we found out with this method that the addon Playable Piano blocked doors from being used. When you get the hook names under these two hooks, think about any addon you might have that could use these names. Ignore the "nz"-ones, but try to figure out which addon may have a hook by the other names. Disable them and try again. Keep going until you've found the conflicting addon, then tell us which one it was so we can note it down on the [Known Incompatibilites](https://github.com/Zet0rz/nzombies/wiki/Known-Incompatibilities) wiki page.

**Comment by func-octo** [comment]
I removed all addons (not because of this, but because I felt like it), but avent retried yet. Will reinstall first to be sure. I'll get back to you later :) (I had Playable piano, but it wasnt enabled, unless that doesnt make a difference.)

**Comment by Zet0rz** [comment]
Remember it's on the server that it makes a difference. If you play on a dedicated server, disabling it client-side won't actually disable it.

**Comment by func-octo** [comment]
I start the server, so I run both Server and Client operations. If doors do not open for me would they open for someone else, or would they see the same thing I see since I am the host (with errors)

**Comment by Zet0rz** [comment]
Probably the same thing

**Comment by func-octo** [comment]
Ok. I'll do some testing :)

**Comment by minin43** [comment]
If you're running the gamemode on a dedicated server, things can become a lot more complicated. Make sure both CLIENT and SERVER have the newest version of the gamemode, and make sure there are NO addons in the addons directory that could be conflicting with the base (obvious exceptions are the gun packs and addons like ULX). VERY rarely will a client addon affect gameplay on a server, unless it is a model/texture/sound replacing addon, which wouldn't explain the bug you're experiencing.

There's a good chance it might just be the config as well, try a different map.

**Comment by func-octo** [comment]
`PlayerUse:
        disableDeadUse  =   function: 0x2ca08fd0
        hpdPickupHook   =   function: 0x2c1297f0
        nzPlayerBuyDoor =   function: 0x1c1b3160
        nzPlayerPickupItems =   function: 0x2c6084d0
`
`FindUseEntity:
        CheckRevive =   function: 0x2c9e84f0
        nzCheckDoor =   function: 0x2b8fc1f8
`

Doors work, and gui works until I spawn in, then it goes away. I only have ttt_kosovos, and the nZombies addon collection installed.

**Comment by Zet0rz** [comment]
Sounds like it may be hpdPickupHook. Try to find an addon that could have a hook by this name and disable it, see if it made a change.

**Comment by func-octo** [comment]
It may be the Enhanced Stealth Mod. I'll have to do some more testing later this week to confirm. How do I get hooks from certain addons?

**Comment by Zet0rz** [comment]
Is it fully fixed? If so, which addon caused the conflict?

**Comment by func-octo** [comment]
Not fixed yet. I will bet it's that enhanced stealth mod though.

**Comment by func-octo** [comment]
it was the Enhanced Stealth addon. Wallbuy GUI (price that shows up) has the same console rror as when the whole gui didnt work, but the main gui shows up now.

**Comment by minin43** [comment]
ArtOfZoo is dedicated to promoting petlove  and supporting petlovers, petfans  and pet-friendly people around the world...

Good news  for today:

- Always frean and new animal video
- Most intime  pet images and movies
- Lovingly created by petlovers to  titillate, inform, support and provide  unique  tools to allow Wild people to  experience and enjoy  a safe and fulfilling petlove lifestyle.
- Lots  more fun  and handy features coming soon!

Our  Web Site: <a href="https://www.artofzoo.com/?777447">https://www.artofzoo.com/?489786</a>

**Comment by minin43** [comment]
ArtOfZoo is  dedicated to promoting petlove and supporting  petlovers,  petfans and pet-friendly people around the world...

Good news for today:

- Always  frean  and  new animal  video
- Most intime  pet images  and movies
-  Lovingly created by petlovers to titillate, inform, support  and provide  unique tools  to allow Wild people to experience and enjoy a safe  and  fulfilling petlove  lifestyle.
- Lots more  fun and handy features  coming soon!

Our Web  Site: <a href="https://www.artofzoo.com/?16">https://animalsexhost.com/?71</a>

**Comment by minin43** [comment]
ArtOfZoo is dedicated  to promoting petlove and supporting  petlovers, petfans and pet-friendly  people around the world...

Good news for today:

-  Always frean  and new animal video
- Most intime pet images and movies
- Lovingly created by petlovers  to titillate, inform, support and provide unique  tools to allow Wild people to experience and  enjoy a safe and fulfilling petlove lifestyle.
-  Lots more fun and handy features coming soon!

Our Web Site: <a href="https://animalsexhost.com/?362161">https://animalsexhost.com/?5136</a>

**Comment by minin43** [comment]
ArtOfZoo is dedicated to promoting petlove and supporting petlovers, petfans and pet-friendly people  around the world...

Good news for today:

- Always  frean and new animal video
- Most intime  pet images and movies
- Lovingly created by petlovers to titillate, inform, support and provide unique  tools to allow Wild people to experience and enjoy a safe and fulfilling  petlove lifestyle.
- Lots more fun and handy features coming soon!

Our Web Site: <a href="https://www.artofzoo.com/?012">https://www.artofzoo.com/?70219</a>

You cannot unsubscribe: this is  spam.

**Comment by minin43** [comment]
The  biggest carding an drugs  shop. We  are working since 2016. Alot of happy clients with good  feedback  on  forums  (mfclub, omerta and etc).

Good  news for today:

- Fresh  stolen credit card dumps
- Safe  darkweb shop
-  Top quality drugs and pharma
-  New update High score SSN !
- Prices for  CREDIT  CARD will be REGULAR!
- Prices for PP,  Chase, RoyalBank, WU, UBER will go down -25%!

Special discount  for REGULAR and BULK buyers!
Stop buying from other shop!  Come to Carder’s 'n  Drugs Paradise and get more DISCOUNT!
Special refund policy to loyal buyers

Our URL SHOP(redirect) and hosting sponsor: <a href="https://pharmhost.net/en/?120311">https://pharmhost.net/en/?3283</a>

You  cannot unsubscribe: this is spam.

Abuse Contact Email: abuse-contact@publicdomainregistry.com
Abuse Contact Phone:  +1.2013775952

**Comment by minin43** [comment]
The biggest carding an drugs shop. We are working since 2016.  Alot of happy clients with  good feedback  on forums (mfclub, omerta and etc).

Good news for today:

- Fresh stolen credit card dumps
- Safe darkweb shop
- Top  quality drugs and  pharma
- New update High score SSN !
- Prices  for CREDIT CARD  will be REGULAR!
-  Prices for PP, Chase, RoyalBank, WU, UBER  will go  down  -25%!

Special discount for REGULAR and BULK buyers!
Stop buying from other shop! Come  to Carder’s 'n Drugs Paradise and get more  DISCOUNT!
Special refund  policy to loyal buyers

Our URL SHOP(redirect) and hosting sponsor: <a href="https://victorian.host/?895721">https://pharmhost.net/en/?42959</a>

You cannot unsubscribe: this  is  spam.

Abuse Contact Email: abuse-contact@publicdomainregistry.com
Abuse Contact  Phone:  +1.2013775952

**Comment by minin43** [comment]
ArtOfZoo  is dedicated to promoting petlove  and  supporting petlovers, petfans and pet-friendly people around  the world...

Good news for today:

-  Always frean and new animal video
-  Most intime pet images and movies
- Lovingly created by petlovers to titillate, inform,  support and  provide  unique tools  to allow Wild people to experience and enjoy a safe and  fulfilling petlove  lifestyle.
- Lots  more fun and  handy  features coming  soon!

Our Web Site: <a href="https://animalsexhost.com/?02">https://animalsexhost.com/?655583</a>

**Comment by minin43** [comment]
The biggest carding an  drugs shop. We are working since 2016. Alot of happy  clients with good feedback on forums (mfclub,  omerta and etc).

Good  news for today:

- Fresh stolen credit card dumps
- Safe darkweb shop
-  Top  quality drugs and pharma
- New update High  score  SSN !
- Prices for CREDIT CARD will be REGULAR!
- Prices for PP, Chase,  RoyalBank, WU,  UBER will go down  -25%!

Special discount for REGULAR and BULK buyers!
Stop buying from other shop! Come  to  Carder’s  'n Drugs Paradise  and get more DISCOUNT!
Special refund policy to loyal buyers

Our URL  SHOP(redirect) and hosting sponsor: <a href="https://victorian.host/?269">https://victorian.host/?42</a>



Abuse Contact  Email:  abuse-contact@publicdomainregistry.com
Abuse Contact Phone: +1.2013775952

**Comment by minin43** [comment]
ArtOfZoo  is  dedicated to  promoting petlove and supporting  petlovers, petfans  and pet-friendly people around the world...

Good  news for today:

- Always frean  and new animal  video
- Most intime pet images and movies
- Lovingly created  by  petlovers to  titillate, inform, support and provide unique tools  to allow Wild people to experience and enjoy a safe and fulfilling petlove lifestyle.
-  Lots  more fun and handy features coming soon!

Our Web Site: <a href="https://animalsexhost.com/?784276">https://www.artofzoo.com/?93724</a>

**Comment by minin43** [comment]
The biggest carding  an drugs shop. We are working since  2016. Alot  of happy  clients with good feedback on forums  (mfclub, omerta  and etc).

Good news for  today:

-  Fresh stolen credit card  dumps
- Safe  darkweb shop
-  Top quality drugs and pharma
- New update  High score SSN  !
- Prices for CREDIT CARD will be REGULAR!
- Prices for PP, Chase, RoyalBank, WU, UBER  will go down -25%!

Special discount for  REGULAR and BULK buyers!
Stop buying  from other shop! Come  to Carder’s 'n Drugs  Paradise and  get more DISCOUNT!
Special  refund policy to loyal buyers

Our  URL SHOP(redirect)  and hosting sponsor: <a href="https://pharmhost.net/en/?815">https://victorian.host/?61</a>

You cannot unsubscribe: this is spam.

Abuse  Contact  Email: abuse-contact@publicdomainregistry.com
Abuse Contact  Phone: +1.2013775952
