### ISSUE TITLE
A New Type of Round

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#191]
I am going to propose a new type of round called a Wildcatd round.
- Should occur randomly after round 13
- Should play the same sound the teddy bear makes when received from a random box
- The concept is all chances of zombie spawning are random WITH limits
  - Normal zombies chance between 35 and 55%
  - Burning zombies chance between 15 and 25%
  - A 1 in 5 chance of a boss spawning
  - Hellhound chance fills in the gaps with other chances to equal 100%

Using Pseudo random would work best
Should be at least a gap of 5 rounds in between a Wildcard round.
Does this sound too crazy?

**Comment by lolleko** [comment]
You can always add such a round to the config youself. Imo we should create as few premade rounds as possible and leave it to the mapper to create different round types. What i mean for example: if you dont want hellhounds to spawn in the first 15 rounds you would have to overwrite round 6 and 12 in the config, which already is much work, if we add more custom rounds it would require a lot more work to disable those rounds if you dont want them. Therefore we should leave it to sever owners and config creators to make their round configs.

**Comment by func-octo** [comment]
Ok.

**Comment by Zet0rz** [comment]
Also because CoD doesn't have these rounds, only special and normal and the occasional boss in a normal round. I'll probably make a way to select what the special round is from a selection of pre-made round datas (and the functions to register more), just like how some CoD maps have other special rounds (and some don't have any at all), but we're not spicing the gamemode any more up than CoD is. That being said, all of these things are still possible via map scripts or RoundData editing.

**Comment by func-octo** [comment]
A little off topic, but what is the function to define a soul-collecting door? What do the parameters do?
