### ISSUE TITLE
Including 'Vigor Rush' Perk?

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#204]
Any plans to add in the new Vigor Rush perk from BO3? That would be interesting even though i have no idea what it does.

Also some good links for Easter egg songs.
1. https://soundcloud.com/lazerhawk/massacre
2. https://soundcloud.com/lazerhawk/these-streets
3. https://soundcloud.com/lazerhawk/another-chance
4. https://soundcloud.com/lazerhawk/sets/skull-and-shark

**Comment by Zet0rz** [comment]
Vigor Rush seems to me like a custom perk from custom zombies in World at War, I've seen it in Leviathan. I don't think it is from BO3, especially not since Zetsubou no Shima didn't have any new perks, and that just came out a month ago. There's a long time till next DLC. 

That being said, Widows Wine is an official perk we're missing. That's mainly because of the model. As to these custom perks, I did have an idea to after release create a seperate addon "nZombies: More Perks" or something. The perk system allows you to script your own like an addon.

**Comment by func-octo** [comment]
Neat.
