### ISSUE TITLE
path follow error

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#212]
my server console ( and when put in single player console) is screaming about how in nz_zombiebase around line 711 "nav" is a nil value. the zombies ability to chase people is crap. and on top of that the server will crash after 60 seconds of this.

bottom line, fresh download of what you have in the master workshop does not work. i was hoping for better considering the master changes has not been updated in a month and it still spawns in more mystery boxes than it should.

i do not know what you did to make both the master workshop and the master changes have problems like this but i recommend rolling back something because this is just not good.

**Comment by lolleko** [comment]
No reason to get mad lol. This gamemode is still under heavy development :)

For the branches: Master-Changes is decrepit and will probably removed at some point. master-workshop is the new branch that will be updated.

Also for "the zombies ability to chase people is crap" thing, could you provide information on that, for example map & navmesh you are using or a gameplay clip. Because imo the chasing is just fine and probably the best it will get with the current gmod version.

**Comment by Zet0rz** [comment]
It sounds an awful lot like you have both branches installed on top of each other. Do you have a `lua/entities` folder with the zombies? And the random box spawning too many boxes also sound like you have both branches installed, having two random box modules running at the same time. Otherwise give me the full error and I will look into it :)

**Comment by Zet0rz** [comment]
Closing this. You are not reporting back with information we need to fix this, so we will stick to our assumption which is that you have overlapping installations. Also no information on why zombies are crap (they really are just as good as gmod allows), and no info on the crashing.

**Comment by func-octo** [comment]
>  Also no information on why zombies are crap

Not that they are. Sure, some improvement like animation freezing (I know it's unknown how to fix it at this point) is always appreciated, but they look awesome.
