### ISSUE TITLE
Zombie Decapitation Suggestion

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#223]
I haven't gotten to see decapitation yet, but does it have a blood "explosion effect" (When the head is gone, there should be a small blood shower where the head used to be.)? If it doesn't, it would be neat, but I don't know what resources it takes for that to happen.

**Comment by func-octo** [comment]
@lolleko I think I found the solution to the eye problem. Just set the eye position below the floor.
https://developer.valvesoftware.com/wiki/Eye_Position_Setup

**Comment by OctothorpeObelus** [comment]
...

**Comment by Zet0rz** [comment]
We are both busy at the this time and progress is slow. I don't even have time to launch the game, much less test whether blood appears. Also that link to eye position setup is related to modelling, not on-the-fly lua editing. We have the functions we have, which only allow us to modify size and position of bones. The problem is finding which bone the eyes are attached to. Shouldn't be too hard once we actually get the time to test things out.

**Comment by func-octo** [comment]
Ok. Good luck to you then :)
