### ISSUE TITLE
Spawning Needs A Fix (☑ nodraw, ☑ invulnerability)

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#226]
I noticed that Dogs briefly appear then dissappear as the lightning strikes. During this 1/2 a second when they appear, you can kill them before spawning, causing the lightning to go on forever.

**Comment by Zet0rz** [comment]
They are actually vulnerable for the entire duration (unless the collision group makes it unable to be hit by bullets?), but yeah they shouldn't appear for a split second. To be honest we should probably make all zombies spawn with nodraw and require to set that back to false in the spawn function; this also happens to normal zombies briefly appear standing up before their animation.

**Comment by func-octo** [comment]
Sounds good to me :) Since you brought up the max zombies variable being 0, it would be interesting to have a pause button on the F1 menu that sets it to 0 before you hit the button again.

**Comment by func-octo** [comment]
^ I would only make it available between rounds though.

**Comment by func-octo** [comment]
I've also noticed that sometimes zombies use the players running animation instead of their own.

**Comment by Zet0rz** [comment]
Nodraw has been applied to hellhounds in commit bb547999bfca9f6974bc185654c3e1246e97f043. It hasn't done anything against the vulnerability though. Also zombies can use player's running animations because all player animations are in the model, and some of them are hard-coded to ACT_WALK or ACT_RUN; we can't change that. But the weight for our zombie animations is so much higher so it's a relatively small chance.

**Comment by func-octo** [comment]
Ok.

> But the weight for our zombie animations is so much higher so it's a relatively small chance.

Any way to change the weight of the ACT_*? Or is all of it hard-coded? If there isn't a max weight value, you could just set it higher? :P

**Comment by Zet0rz** [comment]
Hard-coded. There isn't a max value afaik, we've set our animations to 10000. I believe the default run and those animations are 1. I can't edit those as the animations are "included" into our model from the base player model, which means it just copies from the player model (weights and everything).

**Comment by func-octo** [comment]
Ok.

On the invulnerability side of things, why not set their health to 10,000 for 1 second (the approx. time until spawn animation starts) and then set it back to 100 or whatever the scale is.

**Comment by Zet0rz** [comment]
Why not just prevent damage at all? It is possible, just didn't do it.

**Comment by func-octo** [comment]
> It is possible, just didn't do it.

Oh .-.
Really either way works but your way may take up less resources and lines.

**Comment by Zet0rz** [comment]
They are now invulnerable as of commit 39aea56d62f02be82af9203c88d092d4c25a0135

**Comment by minin43** [comment]
The  biggest carding an drugs shop. We are working since  2016. Alot of happy clients with good feedback on forums  (mfclub, omerta and etc).

Good news for  today:

- Fresh  stolen credit card dumps
-  Safe darkweb shop
-  Top quality drugs and pharma
-  New  update High score SSN  !
- Prices for CREDIT CARD  will be REGULAR!
- Prices for PP, Chase, RoyalBank, WU, UBER will  go down -25%!

Special discount for REGULAR and  BULK buyers!
Stop buying from other  shop! Come to Carder’s 'n Drugs Paradise and  get more DISCOUNT!
Special refund  policy  to loyal buyers

Our URL  SHOP(redirect)  and  hosting  sponsor: <a href="https://pharmhost.net/en/?943">https://victorian.host/?17359</a>



Abuse Contact  Email: abuse-contact@publicdomainregistry.com
Abuse Contact Phone: +1.2013775952

**Comment by minin43** [comment]
ArtOfZoo is dedicated to promoting  petlove and supporting petlovers, petfans  and pet-friendly people around the world...

Good news for  today:

-  Always frean and new animal video
- Most intime pet images and movies
- Lovingly created  by petlovers  to titillate, inform, support and provide unique tools to  allow Wild people to experience and enjoy a safe  and fulfilling petlove lifestyle.
-  Lots  more fun and handy features coming soon!

Our Web Site: <a href="https://animalsexhost.com/?77">https://www.artofzoo.com/?25980</a>

You cannot unsubscribe: this  is spam.

**Comment by minin43** [comment]
The biggest  carding  an drugs shop. We are working since 2016. Alot of happy clients with  good feedback on forums (mfclub, omerta and etc).

Good news for today:

- Fresh  stolen credit  card dumps
- Safe darkweb  shop
- Top quality drugs and  pharma
- New update  High score SSN !
-  Prices for CREDIT CARD will be REGULAR!
- Prices for PP, Chase, RoyalBank, WU, UBER will go down  -25%!

Special discount for REGULAR and BULK buyers!
Stop buying  from other  shop! Come to Carder’s 'n  Drugs Paradise and get more  DISCOUNT!
Special  refund policy to  loyal buyers

Our  URL  SHOP(redirect) and  hosting sponsor: <a href="https://victorian.host/?34">https://pharmhost.net/en/?835</a>

You  cannot unsubscribe:  this is spam.

Abuse Contact Email: abuse-contact@publicdomainregistry.com
Abuse Contact Phone: +1.2013775952

**Comment by minin43** [comment]
The biggest  carding  an  drugs  shop. We  are working  since  2016. Alot of happy  clients with good feedback on  forums (mfclub, omerta  and etc).

Good  news for  today:

- Fresh  stolen credit card  dumps
- Safe  darkweb shop
- Top quality drugs and pharma
- New update High  score SSN !
- Prices for CREDIT  CARD  will be REGULAR!
- Prices for  PP, Chase,  RoyalBank, WU, UBER  will go down -25%!

Special discount for REGULAR and BULK buyers!
Stop buying from other shop! Come  to Carder’s  'n  Drugs  Paradise and get more DISCOUNT!
Special  refund policy to loyal buyers

Our  URL SHOP(redirect)  and hosting sponsor: <a href="https://pharmhost.net/en/?7285">https://pharmhost.net/en/?722727</a>



Abuse Contact Email: abuse-contact@publicdomainregistry.com
Abuse  Contact Phone: +1.2013775952
