### ISSUE TITLE
Edit mode

### ISSUE THREAD

**Issue by sethworkman1624** [Zet0rz/nzombies#227]
I see something about an edit mode in the fixes but ive looked for a long time and can find nothing that has to do with editing

**Comment by Zet0rz** [comment]
Uuhhmm what? If you could point to an example I'd know what you're talking about.

**Comment by func-octo** [comment]
I think he means Creative Mode. It has been called Edit Mode in the past from Alig's version.

**Comment by sethworkman1624** [comment]
How do you get to creative mode?

**Comment by sethworkman1624** [comment]
Never mind checked scripts and found the chat commands

**Comment by func-octo** [comment]
Easier way is to hit F1 (shows the menu you see when you join a map) > Settings Gear > Creative Mode
Follow same steps to get back to survival (play mode).

**Comment by func-octo** [comment]
Or yeah, /create...

**Comment by Zet0rz** [comment]
I plan on making Creative Mode a main button next to Ready Up, and then replacing the Creative Mode button in the settings with an extended dropdown that shows all players allowing admins to give or remove creative from other players (I imagine a list of players with a tickbox you can toggle). We'll want Creative to be a per-player handled system rather than round-based.

**Comment by func-octo** [comment]
Also should close nz_settings upon first round starting.
