### ISSUE TITLE
Exploding Zombies Cause lag and crash my game!!!

### ISSUE THREAD

**Issue by GhostlyMoo434** [Zet0rz/nzombies#247]
So when i kill an exploding zombie my game lags and this is in the console   CreateNoSpawn (spark_shower): only works for CBaseEntitiesNot creating entity 'spark_shower' - too many edicts! (8176 current, 8192 max)

And if i kill multiple Fire zombies at once it crashes my game saying no free edicts

**Comment by Worset** [comment]
Having a similar problem. Also, the explosion of just ONE fire zombie seems way bigger than it should be. Seriously...
![20160627154620_1](https://cloud.githubusercontent.com/assets/18449391/16383863/bbd3ecb8-3c7e-11e6-91b9-24cdba61fcb1.jpg)
That is just ONE zombie. And it freezes the game for like 5+ seconds.

**Comment by Zet0rz** [comment]
I think I may know what it could be that's causing this.

**Comment by minin43** [comment]
It may just be that I have a beefy computer and don't experience this myself when I play, but then causes this issue with combined with monkey bombs (referencing the issue I made).

If you have a fix for this, it may also be a fix for my issue.

**Comment by Zet0rz** [comment]
It was exactly what I thought it was. [This line](https://github.com/Zet0rz/nzombies/commit/b7d2afff09dcd9c753959f4893a7eae05943ee1d#diff-c3ecc4a78e091b1e90138a121a0792beL49) caused zombies who had less than 0 health to be set back to 1 when damaged again, fixing invulnerable zombies. Fire zombies' explosions happened after they lost health but before they died, meaning they health would be set to 1 before their own explosion damage is applied, killing them again, causing another explosion, looping like this until the zombie finally died. This has been fixed in b7d2afff09dcd9c753959f4893a7eae05943ee1d
