### ISSUE TITLE
Server crashing

### ISSUE THREAD

**Issue by Terrible1337** [Zet0rz/nzombies#254]
http://i.imgur.com/jfz0ACH.png

any idea?

after 3 days and happens.

**Comment by Zet0rz** [comment]
Too many entities it seems, it won't create the explosion and then the code fails to modify the explosion. This might be a cleanup issue, it only happens after time? Also using env_explosion was probably a bad idea compared to a util.Effect and util.BlastDamage anyway.

**Comment by lolleko** [comment]
env_explosion is good it has really good physics effects etc. I think the problem is that zombis are chain triggering explosions. Maybe we should remove the ondeath explosion or make zombies immune to the explosions of other zombies. Also i was worried that we hit the entity limit(2048) at some point, we are close than i thought lol.

**Comment by Zet0rz** [comment]
Good call on the physics, I seem to recall BlastDamage doing the same though. And the entity limit is 8192 isn't it (like the screenshot)? And I this doesn't have anything to do with chaining explosions, it's because the env_explosion isn't created as the server is too close to the entity limit. If this only happens after some time, it may be because there's some entities our gamemode isn't cleaning up properly, like rag dolls or maybe these env_explosions.

**Comment by lolleko** [comment]
Limit is 4096, 2048 networked, 2048 clientside etc. I dont see why env_explosion is creating to much entities, its jus one entity and it would really suprise me if the garbage collection fails to delete it. Ragdolls are cleintside only so tehre shouldnt be a problem witht ath either.

**Comment by lolleko** [comment]
Can you run `lua_run print(#ents.GetAll())` before the crash / in a round on the map. And give us that number?

**Comment by Zet0rz** [comment]
Probably a good idea, but the screenshot says how many there are and what the max is (which is for some reason 8192) and refuse to create any more entities. This is an entity limit problem. Could be your server with too many addons, could be your config with too many props, or could be the gamemode with bad cleanup/leftover entities.

**Comment by Terrible1337** [comment]
I have 1163 entities yet.

http://i.imgur.com/UvcK76s.png

**Comment by Zet0rz** [comment]
Is this problem only occuring after some time or always happens?

**Comment by Terrible1337** [comment]
only 1st time since gamemode is updated.

**Comment by lolleko** [comment]
The entity limit for maps is 8192, game entities is 4096. So maybe env_explosion counts towards map ents. How big is the map you are using?

**Comment by Zet0rz** [comment]
> only 1st time since gamemode is updated.

What I meant was how long the server's been up when this happened. You said this:

> after 3 days and happens.

So it makes me think you mean that the server was running 3 days straight and then this crash. I want to know whether this happens always (on the current update) or if it takes time to happen.

**Comment by Terrible1337** [comment]
lolleko, Im using map called "rp_downtown_v4c" seem big the map as well but it's 24/7 Map without change to other the map.

Zet0rz, it's current the update, i tested the env_explosion the zombie burning that its creating new entity id but old entity didn't get delete it after dead or re-ready when every human is dead.

**Comment by Zet0rz** [comment]
From my own testing, env_explosions do get removed right after exploding. You sure your installation isn't bugged? Or something is preventing the entity from being removed by firing "Kill" on it?

**Comment by Terrible1337** [comment]
I was reinstall the garry's mod server. I tested with latest version so works perfectly I think maybe cause the lua conflict or something.

Thanks.

**Comment by func-octo** [comment]
@Terrible1337 I could make different configs for that map so that it isn't always the same :)
