### ISSUE TITLE
Mismatch System - Gun List

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#256]
I have realized that if the mismatched system comes up, you can just replace the missing gun with an already existing one, possibly creating will buy duplicates and higher chances in the random box. It would be great if you remove all guns from the drop-down list that are already in the box (for random box mismatch) and all guns already on the wall are also removed from the list (for wall buy mismatch)

**Comment by Zet0rz** [comment]
Right I see what you mean. At the moment, duplicate wall buys shouldn't really be a problem (you can have the same gun multiple places), and the random box is going to change into a weighted system eventually, at that point it can't get duplicates since the weapons would be the keys in the table, not the values, so I will not fix this until I change it anyway :P

**Comment by func-octo** [comment]
Ok :D
