### ISSUE TITLE
A couple errors 

### ISSUE THREAD

**Issue by Zeelotelite** [Zet0rz/nzombies#268]
```
[ERROR] gamemodes/nzombies/gamemode/ragdoll/cl_zombierags.lua:7: attempt to call method 'GetDecapitated' (a nil value)
  1. unknown - gamemodes/nzombies/gamemode/ragdoll/cl_zombierags.lua:7


[ERROR] gamemodes/nzombies/entities/weapons/nz_perk_bottle/shared.lua:151: attempt to call method 'SetUsingSpecialWeapon' (a nil value)
  1. unknown - gamemodes/nzombies/entities/weapons/nz_perk_bottle/shared.lua:151


FCVAR_SERVER_CAN_EXECUTE prevented server running command: use

C_BaseEntity::UnlinkFromHierarchy(): Entity has a child with the wrong parent!

[ERROR] gamemodes/nzombies/gamemode/ragdoll/cl_zombierags.lua:7: attempt to call method 'GetDecapitated' (a nil value)
  1. unknown - gamemodes/nzombies/gamemode/ragdoll/cl_zombierags.lua:7
```

Occasionally if you're reviving someone, then you get downed while still reviving them, you're weapon will stay as morphine, then you'll keep reviving them but the bar just keeps going and going, they don't die, and when you get revived they get revived also, But you lose your guns because of the morphine glitch. 

When new players join the server at high rounds, they just get destroyed, and keep on getting destroyed, is there a way that if someone "drops in" at a specific round like.. 

round 1 = 500 points, 

round 5 1000 points

Round 10 1500 points, and so on 500 extra points per 5 levels

Server randomly crashes, i haven't figured out if its the gamemode or my host doing it. cpu usage stays around 60ish, i'll be watching for lua errors on this.

**Comment by Zeelotelite** [comment]
Updated

When you pick up a ray gun, and you try swapping it out, it swaps out your other gun rather to the ray gun

Some players have been experiencing issues with not having access to melee(knife\crowbar)

**Comment by Zet0rz** [comment]
> Downed keep reviving until revived

The revive system does need some more verification checks and should cancel out when it fails.

> New player higher rounds, more points to spawn

Not going to happen. CoD does not do this, however if you want it, it should be fairly simple to do with an autorun script. `player:GivePoints(number)`

> Server randomly crashes

Random server crashes is typical for all sorts of gamemodes, but we've had a few reports of them specifically for this. It may just be because the gamemode is handling so much at once, but to resolve it we'll need a crash log to determine what it even is in the first place.

> When you pick up a ray gun, and you try swapping it out, it swaps out your other gun rather to the ray gun

Not specific to the ray gun (or is it for you?), we've had other reports regardless of weapon. It makes no sense though, it's like the invincible zombie and the can't reload bugs - stuff that really should work code-wise but just doesn't.

> Some players have been experiencing issues with not having access to melee(knife\crowbar)

Known cause of ping/net loss as well as not having any ammo (because gmod!). Should be fixed with the Prediction update for special weapons.
