### ISSUE TITLE
Invisible zombie spawns when in creative mode and repeat reload animation

### ISSUE THREAD

**Issue by GhostlyMoo434** [Zet0rz/nzombies#274]
so this bug happen when i was in the middle of making a map,I thought nothing of it until i started testing my map and i found out when my gun was still had a mag in it,it would not reload but if i reload when the mag is empty is repeats the reload animation so i don't know what was up but i knew this was bad cause it did in other map configs as well so im seeking help

**Comment by Zet0rz** [comment]
Can you tell us how many weapons you have installed? If you don't know how, check the FAQ on the workshop page:
http://steamcommunity.com/workshop/filedetails/discussion/675138912/357288572118639985/

The invisible zombie spawns could be because you have preview on. Try toggling it off in the Invisible Wall tool or Damage Wall tool.
