### ISSUE TITLE
Soul Catcher Multi Tool

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#275]
I realize you could script this in, but no one has used it yet given that they do not know how to use it. It would be great to have a tool that creates a soul catcher with the given settings, and should be placed on doors, or if in advanced mode, placed like an invis wall.

**Comment by Zet0rz** [comment]
Not going to happen. The Soul Catcher was never built to open doors or walls and is too advanced for common tool usage. It wasn't even meant to be scripted, it was just for convenience for map scripting.

Also it has already been used in the Breakout map script:
https://github.com/Zet0rz/nzombies/blob/master-workshop/lua/nzmapscripts/nz_ttt_kosovos%3BBreakout.lua#L159-L193

It should be noted, map scripts _are_ advanced. **They _are_ for lua scripters only.** Don't try making a map script because it sounds cool if you can't script in lua. On top of that, map scripts has the potential to break everything in the gamemode since it is direct lua code, so special cleanup has to be made as well for it to not be leftover in the next game.
