### ISSUE TITLE
invincible zombie bug is now worse

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#278]
so i have no idea what you did but now the invincible zombies are worse.
1) they used to not do damage to players, they do now
2) they still do not give points for shooting it.
3) my special made function to detect and remove them no longer works. AKA their health is no longer under 0 so it does not pick up on them being invincible.

TL;DR- change it back.

**Comment by Zet0rz** [comment]
You don't add a TL;DR to a post this short lol

Anyway, the latest update didn't do much to counter the invincible zombies at all. Basically, people reported that it seemingly happens due to instakill, so I made instakill always set the zombies' health to 1 just before the damage is applied. This was meant to prevent them from going negative, which, according to this, actually works. We now know it is not negative health, and that instakill/health setting actually runs on these zombies. 

To get any closer to the actual cause we'll need to encounter an isolated case of this, notice if the zombie has already "died" and given points before or not, and whether or not damage hooks are actually called on it. We need to determine what triggers this state, what their stats are, and whether or not they count in round progression.

**Comment by lolleko** [comment]
Your timer fix, fixed the bug not the defect (and timers are inefficient and bad style) :D It doesn't work any more because zombies with negative health will get their health set to 1 again.

`if nzConfig.ValidEnemies[zombie:GetClass()] and zombie:Health() < 0 then zombie:SetHealth(1) end`

Maybe we should just call zombie:Kill() instead of zombie:SetHealth(1)?

Because i believe with the current solution  there could be a scenario where the zombie gets negative health, then gets the health set to 1 and the gets negative health again, then health = 1 again... 
=> zombie never dies.

**Comment by Zet0rz** [comment]
Thing is, right below it it does `dmginfo:SetDamage(zombie:Health())`, which means the damage should be set to 1, and the zombie should hit 0 health exactly. This was also the case before it was set to 1 though. Zombie:Kill() might work, I'll try that when I continue coding.

**Comment by Zet0rz** [comment]
Check if it works now, it now uses Kill
