### ISSUE TITLE
Grenades don't work with Who's Who

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#287]
Grenades don't work with Who's Who

**Comment by func-octo** [comment]
Any errors or it just doesn't happen?

**Comment by minin43** [comment]
I believe there was an error. I think it had something to do with attempting to call a "special weapon" when there was "none in your inventory" or some verbage similar.

Just, Zet0r, try it out yourself and you should see it in console.

**Comment by Zet0rz** [comment]
I did not encounter any problems with the grenades and Who's Who by itself in the development branch, so the changes in that has most likely fixed it. Unless the bug is a special odd case? I only tested by giving myself grenades and Who's Who, then dying and respawning to see if they worked which they did.

**Comment by minin43** [comment]
Nono, WHILE in Who's Who thing. I was in the revive state (running around with the starting weapon) and I couldn't throw any grenades.

**Comment by Zet0rz** [comment]
I checked the code and it just reruns the player class' loadout function which does give grenades. Maybe you were out of ammo or had the grenade failsafe convar on? Try it on the dev branch and see if it works with the reworked grenades (if you get a chance)
