### ISSUE TITLE
Other players can't build in Creative

### ISSUE THREAD

**Issue by SarinaNubbs** [Zet0rz/nzombies#288]
When I force players into creative, they can't do anything other than grab props and that's it,
They can't sprint, fly, open tool menu nor building menu

**Comment by Zet0rz** [comment]
Have replaced most IsSuperAdmin checks with IsInCreative, so this should fix it. The only things still super admin is loading/saving, and the Context menu right click interfaces (which I plan to completely replace soon)

**Comment by Zet0rz** [comment]
The changes has been committed to the development branch, which you can play if you want. Just know that stuff might be broken there, but also that playing it helps me fix the stuff I wouldn't come across myself. Otherwise, it'll be part of the next update although that update is pretty big and is still missing a lot of stuff, so it might take a while.

**Comment by SarinaNubbs** [comment]
Ah alright, cheers.
Keep up the good work.
