### ISSUE TITLE
I can`t buy any perks D: +how to use grenades?

### ISSUE THREAD

**Issue by kazutaka-z** [Zet0rz/nzombies#296]
i played around with the settings for the amount of perks allowed to be bought but i did not work so i changed them back to the original settings and still cannot buy perks. When i go to wunderfizz it says "CANNOT BUY ANY MORE PERKS"

**Comment by Zet0rz** [comment]
You sure it's not set to 0? It works just fine on my end.

**Comment by func-octo** [comment]
Ok. Well since a lot of people don't seem to know how to use the current grenades, @Zet0rz  could add a notice to the F1 menu in a "Help" menu. Anyway, to use grenades, enter these into the console. The keys can be changed but I find these to be best.

`bind g +grenade1` for standard grenades (white grenade icon)
and
`bind b +grenade2` for special grenades (red grenade icon, monkey bombs)

**Comment by Zet0rz** [comment]
It will change with the next update to not require binds. Instead, it'll be hardcoded to KEY_G and KEY_B (and KEY_V for knife). I could probably make it bindable in some menu, but I don't think I need to bother.

**Comment by kazutaka-z** [comment]
The binds are not working. am i supposed to input the command in GMod Console?

**Comment by kazutaka-z** [comment]
also don`t hardcode knife i like MOUSE 3 as knife (for me atleast)

**Comment by func-octo** [comment]
Yes, use the gMod console, not a server console (if that's what you were trying)

**Comment by kazutaka-z** [comment]
The binds are not working D: idk why, please add to a page to the wiki explaining how to setup nZombies controls and everything and if there is a wiki page on exactly that please send it to me,
BTW Thank you for making/helping make this gamemode for GMod 13.

**Comment by Zet0rz** [comment]
Sounds like the perks thing is fixed. The bindings are shown in the FAQ on the workshop page, but will soon change to not require global key binds.
