### ISSUE TITLE
Issues I'm still experiencing with the dev branch

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#300]
-The zombie spawning is back to being jank again. I'm sitting in the center of my map writing this in the middle of the round, with 2 zombies left to be spawned and nothing is spawning.
-Grenade's velocity when thrown is friggin' MASSIVE. The things fly across the room like they're some bat outa hell.
-Players are starting the game with 4 grenades
-The mapvote system isn't autorunning at the end of the game
-I cannot cast a vote in the mapvote system
-Mismatch system doesn't get a chance to work after map change
-Client is being sent this error during a map change 

```
[ERROR] addons/nzombies-development/gamemodes/nzombies/gamemode/enemies/sh_ent_ext.lua:48: attempt to index global 'nzEnemies' (a nil value)
  1. unknown - addons/nzombies-development/gamemodes/nzombies/gamemode/enemies/sh_ent_ext.lua:48
   2. include - [C]:-1
    3. AutoInclude - addons/nzombies-development/gamemodes/nzombies/gamemode/loader.lua:33
     4. unknown - addons/nzombies-development/gamemodes/nzombies/gamemode/loader.lua:59
      5. include - [C]:-1
       6. unknown - addons/nzombies-development/gamemodes/nzombies/gamemode/cl_init.lua:2
```

-B as the secondary grenade is a bad idea for any server running ULX, where B is the default key
-This error gets thrown into client console after first throwing a monkey bomb 

```
[ERROR] addons/nzombies-development/gamemodes/nzombies/gamemode/special_weapons/sh_functions.lua:295: attempt to call method 'SetActiveWeapon' (a nil value)
  1. EquipPreviousWeapon - addons/nzombies-development/gamemodes/nzombies/gamemode/special_weapons/sh_functions.lua:295
   2. unknown - addons/nzombies-development/gamemodes/nzombies/gamemode/special_weapons/sh_functions.lua:188
```

-(This is actually an old bug) PaPed weapons aren't having their reserved ammo increased after the PaP

A good thing
-I now see all of the perk bottles when I receive a perk

**Comment by Zet0rz** [comment]
> -The zombie spawning is back to being jank again. I'm sitting in the center of my map writing this in the middle of the round, with 2 zombies left to be spawned and nothing is spawning.

Try using developer 1 to see the debug data of the spawnpoints. See if they get zombies distributed, if they are valid, and if both of the timers are in the negative. Let me know what it generally says.

> -The mapvote system isn't autorunning at the end of the game

It defaults off, you need to set a time for it to auto-RTV. It's nz_rtv_time. You can also try chatcommand /rtv. If it still doesn't work, let me know - it works fine on my end.

> -I cannot cast a vote in the mapvote system

Try pressing the button twice. I've had some times where the first button press is ignored or not updated properly for some reason. The server does still register the vote, it just doesn't send this to the client. I'm looking into it as part of the bugfixes that will be in the main update.

> -Mismatch system doesn't get a chance to work after map change

Doesn't get a chance? As in it all goes too fast? I've made the auto-load file also write the Steam ID of the loading player, it will run mismatch on that player if he's in the server within 5 seconds of launching (when the config loads).

> -Client is being sent this error during a map change

Oh great, one of those errors that happen because the system is shutting down, deleting tables yet still running code that refers to them.

> -B as the secondary grenade is a bad idea for any server running ULX, where B is the default key

It will (hopefully) be bindable by a little window (and saved with a convar) using the KEY_ enums in gmod. 

> -This error gets thrown into client console after first throwing a monkey bomb

SetActiveWeapon is nil? I'll need to see what the game thinks is throwing the monkey bomb, this would happen if ply is not valid or doesn't have a SetActiveWeapon function.

> -(This is actually an old bug) PaPed weapons aren't having their reserved ammo increased after the PaP

Ammo should be maxed when receiving a new weapon, which includes PaP. I'll look into if this has broken along the way.

**Comment by Zet0rz** [comment]
Grenades throw fine for me. If I look straight they will go about 6-7 meters ahead.

**Comment by minin43** [comment]
> It defaults off, you need to set a time for it to auto-RTV

Can it be set for "after ever game"?

> Try pressing the button twice. I've had some times where the first button press is ignored or not updated properly for some reason. The server does still register the vote, it just doesn't send this to the client. I'm looking into it as part of the bugfixes that will be in the main update.

Nope, I tried spamming everything. Nothing registered, and it picked a config at random after the timer expired every time.

> Doesn't get a chance? As in it all goes too fast?

As in, the map loads up, the config loads up, but there's no mis-match popup, wallbuys are just "invalid" crowbars, and mystery box contains a bunch of invalid weapons

> It will (hopefully) be bindable by a little window (and saved with a convar) using the KEY_ enums in gmod.

Can you change it to something else for now? Because B is the ULX key

> If I look straight they will go about 6-7 meters ahead.

It's the bounce that does it. It gets thrown 4-5 meters but then bounces everywhere

**Comment by Zet0rz** [comment]
You can set it to after every game by setting the time really low. As soon as the time passes, and RTV will happen at the end of the game. 

Wall buys are invalid crowbars and invalid box weapons? Are you loading a config you don't have the weapons for? The mismatch system is there for that, but now I think you might get another bug altogether. 

You can change the key manually in your own installation. It's in the special weapons module, look for KEY_B and change it. 

The grenades fly 6-7 meters with bounce and roll for me. As in they explode 6-7 meters ahead of me when looking straight and throwing without priming.

**Comment by minin43** [comment]
> Wall buys are invalid crowbars and invalid box weapons? Are you loading a config you don't have the weapons for? The mismatch system is there for that, but now I think you might get another bug altogether.

No the crowbar is the default model for wallbuys if the game starts with an invalid entity as a wallbuy. The first time I tested out the config vote system, it chose a config at random and I played through it, with most of the guns in the m. box and on the wall being invalid.

**Comment by minin43** [comment]
> You can set it to after every game by setting the time really low. As soon as the time passes, and RTV will happen at the end of the game.

Do you HAVE to play a game first, or is it "as long as a game is currently going on" because otherwise it will be eternally changing if it's set to change every 5 or 10 minutes.

**Comment by Zet0rz** [comment]
It will check if the time has passed in a OnRoundWaiting hook which gets called after each game has finished (after the 10-second game over state), so it will only check once per game played (and once right at the start). If you set it to say 5, it'll only run if a game has ended and 5 min has passed since last vote. Should this be changed?

**Comment by minin43** [comment]
As long as you have to play a game first before doing the vote.

**Comment by Zet0rz** [comment]
> As long as you have to play a game first before doing the vote.

It will only check when entering waiting state (not _during_ waiting state, only when _entering_ waiting state) which _only_ happens at the very start of the server and at the end of each game. Set it to more than a minute and it will always only be after games.

**Comment by Zet0rz** [comment]
All of these things should now be fixed (with the exception of Mismatch not having time to work. I'll look into that, it's all dependent on how long to delay the config loading)
