### ISSUE TITLE
new posible perk!

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#303]
a new perk cola textures pack has come out recently
http://steamcommunity.com/sharedfiles/filedetails/?id=761321077&searchtext=

it it is the Widow's Wine machine!

**Comment by minin43** [comment]
Well have fun coding all those mechanics out. Looks like it'll be hell :\

**Comment by Zet0rz** [comment]
Of course it's possible! And it's planned too! I was actually waiting for this guy to finish the model (it's the same guy who gave us the other BO1+2 perks), but I recently got BO3 myself because mod tools are being made, so I thought I could extract it myself.

Now that he's made the model, I'm gonna ask him for this one as well, but regardless of whether we get it, it's definitely becoming a perk!

**Comment by Zet0rz** [comment]
Permission acquired

**Comment by minin43** [comment]
kewl

As for the bubblegum stuff, it might make a good, seperate, "gamemode extension." Saved on a server-by-server basis (so saved locally), which means people can cheat for this in SP

**Comment by Zet0rz** [comment]
> Saved on a server-by-server basis (so saved locally), which means people can cheat for this in SP

Isn't that a contradiction?

Either way, if I make Gobblegum, it'll be part of the main gamemode. However it'll likely only come with 10-15-ish different ones, with the ability to add more with extensions, similar to how the powerups system works.

**Comment by minin43** [comment]
Saved locally means on a MP server, players wouldn't have access to it, since it's saved locally to the server, but in SP where the player could edit the gamemode on their own, they could cheat for everything. Just thought I'd point that out

**Comment by Zet0rz** [comment]
Ooohhh, you're on about a way to keep track of how many you have? I imagine I'll just make all players have all of them at the same time, and purely give a random one based on rarity. Inventory system would work saving serverside, but it'd be awkward to add some way to get new ones, like would you take donations for X "boxes", would you hand them out based on time ...? and so on.

Edit: It should also be possible to save locally in SP how many you have, it'll just be in a file that the player could edit (which is fine since it'd only count for SP anyway).

**Comment by minin43** [comment]
That would end up happening whether you added support for it or not. The servers need to get donations somehow, this would be one of the few ways to incentivise it.

**Comment by Zet0rz** [comment]
Closing this, Widow's Wine discussion will continue in #304
