### ISSUE TITLE
Traps, Buttons & Logic Part 2

### ISSUE THREAD

**Issue by lolleko** [Zet0rz/nzombies#308]
The curretn trap & loggic system is incomplete here is a list of things that will need to be implemented:
- [x]  Make Traps & Logic Ents available via the entites tab in the Q-Menu
- [x]  Create a Tool for Traps & Logic Ents
- [x]  Make logic entites savable
- [x]  Add Electro-Shock-Defense
- [ ]  Proper model for turret trap
- [x]  COD Button Model
- [ ] Soul Catcher gate
- [ ] Support for entities from other entities ttt_traitor_traps for example

For part one visit: #309 and https://github.com/Zet0rz/nzombies/wiki/Traps,-Buttons-and-Logic-Gates

**Comment by func-octo** [comment]
Could you please make soul catchers easy to use and accessible via the GUI? They should link to entities that activate. If you don't know what that is, it collects kills within a certain radius and after it hits the set amount, activates a trigger used to open doors and things, maybe even freely activate traps :)

**Comment by lolleko** [comment]
Yes i guess i can port the existing soul catcher entity to the "new" format. So you can have the simple soulcatcher that can activate doors buttons and traps. And the complex map script one if you really want something advanced.

**Comment by func-octo** [comment]
Thank you :)

**Comment by Zet0rz** [comment]
I'd like to know: What do you want to use the soul catcher for?

I'm not saying it shouldn't be ported to the logic system, but I have to draw a line somewhere to define what should be Creative Mode doable, and what should be map script exclusive. Making things too easy to use would result in over saturation, removing the uniqueness of it. Imagine how boring all CoD Zombies maps would be if they all happened to have a teleporter you have to link to the mainframe, or if they all had the same soul-catcher PaP objective.

**Comment by lolleko** [comment]
I don't quite get that logic, you want boring maps so other maps are more exciting? 😅 **Not allowing** everyone(no scripters) to use all features, will end up in over saturation, because most of the maps would just the non mapscript features (which aren't to many tbh).

It seems weird to me to put features behind a skill wall(the ability to code), if we can also allow everyone to use those features.

**Comment by minin43** [comment]
Well you have to take into account that handing the tools over when they don't have the know-how is as equally "unproductive" when compared to having the know-how then receiving the tools.

**Comment by func-octo** [comment]
@Zet0rz The reason I'm so fascinated with the Soul Catchers is because they can literally be linked to anything in the map to something happen, and aren't obvious, the only way to tell where a soul cather is is the effect the zombies have when they get killed within a radius of one, making for good easter eggs.

**Comment by Zet0rz** [comment]
> I don't quite get that logic, you want boring maps so other maps are more exciting?

Imagine we make a Teleporter tool. You'd get configs like Dust 2 that has a teleporter from A site to B site despite not fitting the theme at all. And the reason for doing it would just be "because he can". It would reduce the overall quality of configs.

> making for good easter eggs

An easter egg only consisting of soul catchers? And also, with the current logic system you wouldn't be able to do much with its output other than traps and doors.

---

That being said, I had an idea for an alternative option. **A complete logic system implementation**. This would mean _everything_ would have in- and outputs, including perks, wall buys, doors, electricity, win/lose entities, editors, and more. We'd then also have to implement the ItemCarry system into Creative Mode, including spawnpoints, spawners, removers, checkers, much more. It starts getting complicated when we have to pass players around as arguments though, such as a logic entity to check if the player is carrying a certain item ...

Maybe it could be done with keywords such as !activator, similar to Hammer, but it will be a hell of a lot complicated to piece together, and probably resource intensive too.

I imagine entities that would be logic-applicable could have a table like:

``` Lua
ENT.NZLogic = {
    SetPrice = function(ent, activator, arg)
        ent:SetPrice(tonumber(arg))
    end,
    Despawn = function(ent, activator, arg)
        self:SetNoDraw(true)
        self:SetNotUsable(true)
    end,
    Spawn = function(ent, activator, arg)
        self:SetNoDraw(false)
        self:SetNotUsable(false)
    end,
    -- More logical input functions
}
```

And then add a tool which, when shooting two entities shows a popup window that lets you select an output from the first entity's output functions, an input on the second entity's input functions (via dropdowns referencing this table), and a simple text field for arguments. Each entity with logic attached will then need to save along a Logic ID (or some other unique ID) so the logic connections could be recreated on load/cleanup.

Very complicated, likely not worth it. But it'd be the only case in which I'd add teleporter and other easter egg tools.

**Comment by lolleko** [comment]
> Imagine we make a Teleporter tool. You'd get configs like Dust 2 that has a teleporter from A site to B site despite not fitting the theme at all. And the reason for doing it would just be "because he can". It would reduce the overall quality of configs.

Why do you care lol, you don't have to play it :D the workshop ratings will filter bad configs out.
Trying to control what people will create with the tools is pointless. Imagine gmod would block certain features just because there are people that make "bad" add ons with those.

---

I am not sure what you mean by the second part tbh, Wall buys, perk machines, elec switches.... would just have to extend nz_activatable (for input) or nz_button for (input/output). Basically everything you press e on can be easily integrated.

A hammer like I/O system is possible, but i think its a little bit to late for that. I mean this whole mode is so already so much pieced together, there is also no documentation and gmod is slowly dying, so i highly doubt there will be many people actually scripting custom stuff for this mode (beside zombies and mapscripts). And like i said most of the builtin systems can be easily integrated into the current logic system.

**Comment by func-octo** [comment]
@Zet0rz That would be awesome to have something like that, but I know it'd take a lot of time (idk).

**Comment by minin43** [comment]
>  the workshop ratings will filter bad configs out

Not true

**Comment by func-octo** [comment]
> > the workshop ratings will filter bad configs out
> 
> Not true

Actually over time this is true as people play it they rate it.

**Comment by minin43** [comment]
Yea in theory it works.

But gmod is filled with a bunch of tasteless 12 year-olds who hardly care what the quality of a config is. I've joined numerous servers playing on maps that have little to no added scenery/props, horrible NEXBOT navigation, and incredibly stupid design choices, and the workshop just seems to gobble these up. The maps themselves can even be filled with errors.

Those are the highest-rated workshop maps.

//End frustated rant

**Comment by lolleko** [comment]
I get what you mean, but i don't think thats our problem. And i am pretty sure once the gamemode gains some popularity that, there will be some decent servers with good configs.

**Comment by Zet0rz** [comment]
It should be noted that my primary consumer group is the common workshop-player, playing the game in single player or with friends locally. I am not building the gamemode to be a server-type one (although with compatibility to be so).

**Comment by minin43** [comment]
> It should be noted that my primary consumer group is the common workshop-player, playing the game in single player or with friends locally

And for this I am thankful you add what MP-related stuff you do

**Comment by Zet0rz** [comment]
We should make nz_buttons able to be linked to map-buttons like ttt_traitor_button. This will enable players to make use of map traps or use buttons to open secret doors; of course only possible if the config has Gamemode Extensions enabled.

**Comment by func-octo** [comment]
> map traps

xD Deathrun nZombies

**Comment by minin43** [comment]
> map-buttons

How about any of the many many zs_ or zm_ maps? Those have a lot of areas restricted via game progression in Zombie Survival or Zombie Master, which could make great use of that.

**Comment by lolleko** [comment]
Added other gm entity interaction to the todo-list.

**Comment by Zet0rz** [comment]
> How about any of the many many zs_ or zm_ maps? Those have a lot of areas restricted via game progression in Zombie Survival or Zombie Master, which could make great use of that.

Zombie Survival's mostly already there. You can refer to #189 for that. Logic will only be linkable to actual activateable entities, which is basically just the ttt_button for now. Don't know about Zombie Master.

**Comment by Zet0rz** [comment]
Look what I made :D 
![](http://i.imgur.com/1tZZjRW.png)

The handle comes with 4 skins which affect the cagelight; Off, Green, Orange, Red. When you implement this, you might want to add extra keys and values to the model tables of the buttons. Something like `off_skin = 0, ready_skin = 1, on_skin = 2, cooldown_skin = 3` so they can be changed on a per-model basis. Then you might want to add `ENT:OnPoweredOff()` as well. 

``` Lua
ENT:OnReady() -- Powered on/off cooldown (turn green)
ENT:OnActivation() -- When used (turn orange)
ENT:OnDeactivation() -- When it's finished (turn red)
ENT:OnPoweredOff() -- When (and if) the power should go off (turn light off)
```

Model's coming in the content pack update very soon! Only missing a single sound!

**Comment by minin43** [comment]
Awesome!

**Comment by lolleko** [comment]
Looks good!!! Can you send me those models as soon they are done? so I can start integrating them.

**Comment by Zet0rz** [comment]
They're in the content pack update coming out now - they will be in part 2.

**Comment by jaxjaxk** [comment]
i built a working trap system that works great. so far it has telsa, turret, and explosive traps. i did not notice that the dev branch was active so i never noticed people were working on traps when i already got that done. you can do it your way if you want or i can give you the stuff.
all that has to be done to the traps is
1) improve the turret traps so that the laser shows up all the time. also the sweep should be better ( i did take it from ZS and modify it) ( dead code needs to be removed too)
2) right now explosive traps are just explosive barrels that catch fire and then explode. might be nice if the trap spawns in the barrels that explode so they can fall from above and shit.
3) i need a better button model.
4) button should display what trap it is and price

so as you can see i got it all working, just needs touch ups and I'm not a kind of person who does that when there is too much on my plate already.

**Comment by lolleko** [comment]
http://i.imgur.com/VjIfGhE.gif
Tesla / Elektro-Shock traps are almost done.

:-)

**Comment by lolleko** [comment]
Closed for now open a new issue if you encounter any problems with the traps.
