### ISSUE TITLE
More Intuitive Config Saving

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#339]
**Short**
Could you add a menu to the save config, or a new tool that lets us mark props, so we can save parts that arent normally saved in configs?

**Long**
So if you've heard of an addon named Spacebuild, you know it comes with all parts needed to create space ships and stations (these parts are nice and close quarters). Well I was wondering if we could have a menu of what props to save, or an extra tool to mark extra props to save into the config. This way, I can build using other addon props, and can make a zombie apocalypse happen on a space station.

**Extra**
So the way I'm going to get these space station builds into nzombies is by using saves, so I can have the parts in there already (not tested btw). Also, do navmeshes account for frozen props? If not, this idea wont work at all.

**Comment by jaxjaxk** [comment]
ya also i have noticed that mysteryboxes seem to not save as frozen. whenever a map loads the dummy boxes can be pushed by players.

**Comment by Zet0rz** [comment]
Navmeshes are built into the map, so no, they aren't dynamically generated across frozen props. You could of course manually make a custom Navmesh that lets them navigate and include it with your config. 

I'm not entirely sure what you want with this though. Extra props? Parts that aren't normally saved in the config? The config saves the entire creative mode, only map things aren't saved because the map generates them anyways. If you want more props, simply find them in the spawnmenu (use Search or Addons tabs) and spawn them as normal props (like doors). Do you mean like special entities? I don't get what you mean because what you're saying sounds like just more models, and the spawnmenu already has _all models you have installed_.

**Comment by func-octo** [comment]
> and the spawnmenu already has all models you have installed.

Oh in that case, I guess everything should work if done correctly. Thanks :)
