### ISSUE TITLE
Bugged lock doors

### ISSUE THREAD

**Issue by Player53212** [Zet0rz/nzombies#348]
Hey there seems to be a problem with doors that as we try to unlock them in survival nothing seems to happen. Please respond to this issue soon as doors seem to be an integral part of the game mode.

**Comment by Zet0rz** [comment]
What doesn't happen?

**Comment by Player53212** [comment]
Trying to buy doors

**Comment by Zet0rz** [comment]
That didn't quite answer my question. Do you lose points? Do you hear/see the effects? Can you buy perks or weapons with E? What happens if you open a non-locked door (map door)? Do doors correctly auto-open if set to a price of 0?

Also check your hooks table with console `lua_run PrintTable(hook.GetTable())` and list me the names under PlayerUse.
