### ISSUE TITLE
boss spawn

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#354]
why is it that the boss only spawns once? like WTF?

**Comment by Zet0rz** [comment]
There is a bug where the NZBossType field is not set or is cleared on the boss zombie, and that causes its death function to not run which is what sets the next time for it to show up. No clue why it isn't set or where it might get cleared, I found it nil in actual playing but it is always correct in local testing.

**Comment by jaxjaxk** [comment]
looking into it i find that the death function is never run. where is the function even called?

i searched through sever files trying to find where the function is called but found nothing.

**Comment by Zet0rz** [comment]
Boss' death function is called from the damage hook: https://github.com/Zet0rz/nzombies/blob/master-workshop/gamemodes/nzombies/gamemode/enemies/sv_hooks.lua#L67-L80
Specifically line 76 calls the death function. It is only called if the data can be found, as in zombie.NZBossType is set, which happens in the spawn function:
https://github.com/Zet0rz/nzombies/blob/49407298f7e3838fe0cb98469042fe6c9f8d662a/gamemodes/nzombies/gamemode/round/sh_boss_round.lua#L57

From my debug prints, it appears the few times it didn't get called was because zombie.NZBossType was nil, yet any further testing (with no changes to the code) had NZBossType working every single time.

**Comment by jaxjaxk** [comment]
it would appear in the hook
`	hook.Add( "OnBossKilled", "nzInfinityBossReengange", function()
		local round = nzRound:GetNumber()
		if round == -1 then
			local diff = nzRound:GetNextBossRound() - round
			print("Diff here is", diff, diff > 0)
			if diff > 0 then -- If a new round for the boss has been set after the first one died
				nzRound:SetNextBossRound(round) -- Mark this round again
				nzRound:PrepareBoss(diff * 10) -- Spawn the boss 10 zombies later for each round it was delayed with
			end
		end
	end)`

it only sets the next boss round if it is round infinity.
i do not see anything in this hook or code that shows that the death function for the boss is run. i recommend

`	hook.Add( "OnBossKilled", "nzInfinityBossReengange", function()
		local round = nzRound:GetNumber()
		if round == -1 then
			local diff = nzRound:GetNextBossRound() - round
			print("Diff here is", diff, diff > 0)
			if diff > 0 then -- If a new round for the boss has been set after the first one died
				nzRound:SetNextBossRound(round) -- Mark this round again
				nzRound:PrepareBoss(diff * 10) -- Spawn the boss 10 zombies later for each round it was delayed with
			end
		else
		local data = nzRound:GetBossData()
		if data then
			data.deathfunc()
		end
		end
	end)`

as this adds in the death function you defined in the boss_round file but never seemed to have used.
( i proved it was never run with a simple print function)

**Comment by jaxjaxk** [comment]
`function GM:EntityTakeDamage(zombie, dmginfo)` is not even running.....

**Comment by jaxjaxk** [comment]
strange, after changing up a few things it now works flawless. i forgot what i did, i just know i did not do much.
