### ISSUE TITLE
Name Tags

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#369]
There should be a naming system in the tools that name the upgraded weapons instead saying Upgraded *Weapon name*

**Comment by minin43** [comment]
There already is a system in place, it just doesn't use the creative mode tool gun.

**Comment by Zet0rz** [comment]
There is a system and it runs in the code of the gamemode, not in any interface. It will never be an interface or saved on a per-config basis, it was only built in a way so that weapon pack creators could add it to their weapons (along with other special nZombies support), and so that server owners (including players hosting local servers in-game) can change names on their server. 

Eventually the gamemode itself will have all weapons in the official collection named - any other weapons are up to the creators/players to add.

**Comment by DjNathann** [comment]
Alright good to know.
