### ISSUE TITLE
posiblity of SNPCs

### ISSUE THREAD

**Issue by jaxjaxk** [Zet0rz/nzombies#381]
while looking around i found this on the workshop
http://steamcommunity.com/sharedfiles/filedetails/?id=862317093&searchtext=vj+nazi

now i have had some success in the past with using SNPCs and i know VJ snpcs are pretty good. it might be we can reduce lag by using SNCPs instead of nextbots for the zombies. any thoughts?

**Comment by Zet0rz** [comment]
I have never used SNPCs, as far as I know they don't use the Navmesh system which is important for our door-based navigation. Nextbots also seem like the newer, more efficient bots of the two.

**Comment by jaxjaxk** [comment]
hard to say. i have used SNPCs from VJ base that worked great. the reason for most of the lag in this gamemode is due to low frame rate of the clients. i am not sure how to reduce this however i should not be seeing decent lag when 5 people are on with only 30 nextbots.

on the note of SNPCs i do know VJ base SNPCs will gladly work with a navmesh and if they can not get to the player through the navmesh they will use the basic method of NPCs. it would be worth looking into especially considering the workshop is 95% similar to the zombies we use here. (http://steamcommunity.com/sharedfiles/filedetails/?id=862317093) they attack animations and coming out of the ground are all there.

**Comment by minin43** [comment]
If anything, I think an inefficient and taxing base would *really* only affect performance on the server. Client just slows down when you're rendering 200+ entities all quazi-dynamically. I don't believe there's any inherent fault with the selection of NPC.

**Comment by Zet0rz** [comment]
We are sticking to our models. When you say clients lag, that may be from the animation system or from other gamemode rendering executions. I too have noticed a significant frame drop in higher rounds (like 100 -> 25-35, GTX970). I will need to run profiling on the animation system, if it turns out the animations are just intensive (I think it's just that, lots of animated models at one time) I might be able to adjust them in the animation rework I'm working on. 

If we should for whatever reason switch to SNPCs, it'd be a rescripting our bots, not use other people's addons.

**Comment by ghost** [comment]
SNPCs are outdated, and have been replaced by nextbots everywhere from L4D2 to TF2.  There are no real advantages, yet numerous sacrifices, ranging from the janky navigation to their restricted behavior.  IMO, definitely keep using Nextbots
