### ISSUE TITLE
Can we change what PAP camo applies to?

### ISSUE THREAD

**Issue by globalcringe** [Zet0rz/nzombies#385]
Using TFA CS:O. Some guns have special effects and such rendered using transparent textures, like a shine or small bits of lightning. However, this causes issues, shown here:

http://steamcommunity.com/sharedfiles/filedetails/?id=879160007
http://steamcommunity.com/sharedfiles/filedetails/?id=879160043

So, I was wondering, is there something I can do in my guns' lua to remedy this?

**Comment by minin43** [comment]
Is this due to Zet0r not expecting weapon devs to be so stupid, or just a simple oversight...? Only time may tell... /s

**Comment by globalcringe** [comment]
There's no need to be hostile. I'm just trying to find a way to change up camo, and with no documentation I find it pretty difficult.

**Comment by minin43** [comment]
It was a joke.
/s indicates sarcasm in a text. There's no hostility. Pay attention to the wording of what I said, there's non ill intent, there's no anger, no nothin'. I'd remove the comment but I didn do nuffin wrong.

But this is clearly something Zet0r will have to answer. I don't think anyone else knows anything at all over how textures for weapon work.

**Comment by Zet0rz** [comment]
Currently PaP textures apply to a random set of submaterials on the weapon. It has a few banned keywords, of which if the material path/filename contains any, they will not be modified (these words are "scope", "hands", etc). One solution would definitely be to add more keywords into that. It also seems that these submaterials are often unattached attachments suddenly being set visible, so another possible solution would be to modify textures themselves so that materials' visibility aren't set, but rather the drawn image linked to that material.

These are all potential solutions to trying to _automate it_. There are some manual ways to modify them for weapon coders too:
- `SWEP:PaPCamo(vm)`
If this exists, it is called instead of automatic PaP camo application every time the weapon is drawn if it is PaP'd
- `SWEP.PaPMats = {...}`
This is generated when the materials are first modified. Each key (might change to value soon) represent what SubMaterial ID is being replaced with the material. If the table already exists (i.e. coded into SWEP), it will not be overwritten, allowing that table to specify what submaterials to replace.

Automation is a high priority though, as I don't expect weapon creators to code specifically for this gamemode, and want to support as many weapons as possible out-of-the-box.
