### ISSUE TITLE
Double Fire Sale Bug

### ISSUE THREAD

**Issue by minin43** [Zet0rz/nzombies#391]
If Fire Sale is picked up twice, the second while the first is still active, all Mystery Box locations bug out and *all* of them will get the mystery box permanently, although I have yet to test what impact receiving the teddy bear will have.

**Comment by minin43** [comment]
Update: Teddy bear does nothing. The "leaving" animation will play, but the mystery box will just re-appear.

**Comment by Zet0rz** [comment]
This is actually hilarious.

Timer-based powerups should probably not call their init function if already going on, only extend time.

**Comment by Roachisserie** [comment]
This isn't the same bug but it -is- related.

If there's only one box spawn in the map, fire sale still spawns, and it creates a second box over the first one, this is minor at first, but when the powerup runs out the bear pile appears and clips through the first box.

Oh and sometimes in the same situation you can accidentally activate the first box rather than the second, essentially robbing you of 940 points.
