### ISSUE TITLE
Death Machine Error

### ISSUE THREAD

**Issue by DjNathann** [Zet0rz/nzombies#442]
[ERROR] addons/nzombies-master-workshop/gamemodes/nzombies/entities/weapons/nz_death_machine.lua:103: attempt to call method 'RemovePowerUp' (a nil value)
  1. NZSpecialHolster - addons/nzombies-master-workshop/gamemodes/nzombies/entities/weapons/nz_death_machine.lua:103
   2. unknown - addons/nzombies-master-workshop/gamemodes/nzombies/gamemode/special_weapons/sh_functions.lua:489

**Comment by jaxjaxk** [comment]
i think you screwed up more than this. it would seem some functions did not load into the gamemode like RemovePowerUp. check your server consol when you first boot and look for the first error you get.

**Comment by DjNathann** [comment]
not my server its Raven's

**Comment by Zet0rz** [comment]
Sounds like either RemovePowerUp doesn't exist (the gamemode couldn't load the file, look at jaxjaxk's reply), or that the entity it's trying to run it on doesn't have the function (could it be the deathmachine isn't equipped by a player?).

Regardless, this sounds like a bug on your end rather than a global bug (function not existing), as that would've been caught during the very first time the function was created. I might be wrong, but I can't fix something like this unless I too get the bug.

**Comment by DjNathann** [comment]
Happens when someone switches the death machine.

**Comment by DjNathann** [comment]
Try using the funcion of BO3 death machine.

**Comment by Zet0rz** [comment]
> Try using the funcion of BO3 death machine.

?

**Comment by DjNathann** [comment]
Yea i don't know why i said that...

**Comment by minin43** [comment]
>Zet0rz commented on May 18

> DJNathann commented 5 hours

Date: 9/9/2017
