### ISSUE TITLE
nzombies ingame navmesh editor doesn't want to save or work at all

### ISSUE THREAD

**Issue by ghost** [Zet0rz/nzombies#525]
i am able to make the zombies follow the navmesh and stuff yes i can connect and do stuff whatever
but the issue is that when i click ready it still says there is no navmesh when there is one
not only that, when i click save map 
if i make a custom navmesh using the tool nzombies edit mode it doesn't load even though i saved it
is there something i am doing wrong

**Comment by minin43** [comment]
I am willing to bet money you are doing something wrong. Are you saving the nav file? The nav file is *entirely different* from the map's own txt file that you create when in nZombie's creative mode. When you are done editting a nav file, you need to type in server console (this works the same in your client console when playing single player), "nav_save", but without the quotes. There may be a button that does this in nZombies's own nav editting tool, but I find the tool incredibly unreliable and, if it seems nothing is working, I will always double-check saving with command line commands.

Keep in mind, this is different from the nav_generate command, which creates a nav file by scanning the environment of the map. This process is *extremely* resource intensive, as it does this while the client is still loaded.  You will be able to tell when gmod is creating a nav file, because either your gmod will crash or you'll get 2 fps the entire duration.

**Comment by DjNathann** [comment]
nav_generate.

Did not work?

nav_mark_walkable

then

nav_generate.

and then.

nav_save.

**Comment by Zet0rz** [comment]
nav_save is what you're missing. The toolgun for nav editing does nothing but call the nav_ console commands for you.
