### ISSUE TITLE
NOT A BUG/ISSUE: Steam Group

### ISSUE THREAD

**Issue by sh4d0w59** [Zet0rz/nzombies#581]
I made a unofficial nzombies steam group for people to discuss stuff about the gamemode, features they'd like to see added to it, and to get the word of Nzombies out to more people.  If anyone in the github wants to join and contribute to any discussions in the group feel free to join.  If any of the devs want to join I'll throw you in the mods/admins section of the group so you can be heard/seen better.  Link: http://steamcommunity.com/groups/uonzombies  Sorry if I've broken any unspoken rules.  Take this down if you don't feel it should be here.

**Comment by minin43** [comment]
While I'm not opposed to the idea of a gamemode-specific steam group for the gamemode, I feel it would be best if it's left to Zet0r to make and manage *only if he wants to,* with the assumption being no one makes one because he doesn't.

I can see a lot of confusion and miscommunication in the future if the steam group is ran from an entirely different group of people than the group of people (or person, rather) who made the gamemode in the first place.

But that's just my opinion.

**Comment by sh4d0w59** [comment]
@minin43 I'll leave the group up until a new one is made by @Zet0rz or if told otherwise by @Zet0rz.  I'd like to get more attention to the gamemode so that it rises in popularity.  The group is structured to encourage people to view the github and get involved instead of just blowing the group up with bug posts that can't be fixed by me or my friends.  More popularity could lead to more people being able to commit to the gamemode.  Idunno, just my two cents.  

[EDIT]  No hostility intended towards you @minin43 just conveying my opinion.

[DOUBLE EDIT] I'd love to see @Zet0rz join the group himself or make an official group for discussions regarding balancing and anything else that may crop up.
