### ISSUE TITLE
Points aren't given when i kill zombies

### ISSUE THREAD

**Issue by conbubz** [Zet0rz/nzombies#586]
when i kill zombies i dont get any points and the zombies amount doesn't go down. why is that?

**Comment by minin43** [comment]
If that's happening, you have either installed a conflicting addon or you've editted the gamemode in some way.

[In the wiki, there's a page listing addon incompatibilities.](https://github.com/Zet0rz/nzombies/wiki/Finding-Conflicts-&-Known-Incompatibilities) Take a look and see if you have any installed listed on the page. Otherwise, post any errors you're getting in server console.

EDIT: You most likely have damage numbers installed.

**Comment by conbubz** [comment]
im mean my theory was it could be vj base because as far as im concerned i dont think i have any damage numbers on but i'll look on my addons

**Comment by conbubz** [comment]
i have narrowed it down to an addon called cturiselection (i think it only started when i had it) might've been the phantom ruby swep as well
