### ISSUE TITLE
Post-Workshop Release: Model packs for zombies or players (Enhancement, Question)

### ISSUE THREAD

**Issue by func-octo** [Zet0rz/nzombies#99]
So is there any intention to add support for model packs on the workshop (Ex. ScriptnLua's TF2 Model pack. Where description would include nzombies. Basically this example is made specifically for this gamemode) where you could choose an installed pack? If so, you could check for the word nzombies in the title of it (or description if you can). That way when you add the model settings for the zombies maybe this would be useful. Or you could do it without filters for any model pack the user has installed.

**Comment by Zet0rz** [comment]
There is, but not something it'd do automatically. The way I see this being done would be to make a function
`AddModelPack(id, {table of models}, animationid)`
Where ID is a name you want to give it (Which will show up in the Map Settings tool), the table of models is like it says, a table of models. Possibly even a table of models where each is a another table of skins and bodygroups (but maybe not). AnimationID is the ID of a table of animation data (stuff like speed thresholds and such), because without it it'd error because it's trying to play "nz_walk" or something. I plan on coding these Animation tables myself, on being "nz" which are the ones we're using (for models that includes ours for its animations), and "default" that runs normal ACTs and shared gmod sequences. You could add your own of that as well.

To install it with your model pack you'd then include an autorun script that calls this function if the gamemode is "nzombies3". Then you'd pick it for your config in the Map Settings tool.

**Comment by minin43** [comment]
Don't the NPCs need the animations for it to look nice? They don't need it to function, as we saw with the hellhounds, but wouldn't it look crappy without all of the animations?

**Comment by Zet0rz** [comment]
I would highly recommend using the normal zombies, but some people could find a way to port say L4D or TF2 zombies, which would then have their own animations. But any model rigged to a Valve Biped (standard skeleton) could just be recompiled with `$includemodel "zombie_rerig_animated.mdl"` and it'd have all the animations of our model. I might do this later to make "expansion themes" so you can pick stuff like Civilians or something. Not all maps work with Nazi soldiers xD

**Comment by minin43** [comment]
Could you do the head crab zombies just minus the headcrabs? Change the model based on their life or speed and you could use the zombine models or something

**Comment by Zet0rz** [comment]
I always work towards max compatibility, so default gmod models (of any kind) should work, as you can just load them in like any other. You just wouldn't have the nz animations unless you recompile the models.
